; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_feather_esp32s3]
platform = espressif32
board = adafruit_feather_esp32s3
framework = arduino
upload_speed = 921600   ;【固件 / littlefs 上传波特率】烧录速度
monitor_speed = 115200  ;【串口监视器打印波特率】只影响日志输出，和上传快慢无关！

board_build.flash_mode = qio
board_upload.flash_size = 32MB
board_build.arduino.partitions = large_littlefs_32MB.csv
board_build.filesystem = littlefs
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L

# 关键：上传文件系统时使用 --no-stub
uploadfs_flags = --no-stub

build_flags = 
	-Iinclude
	-DARDUINO_USB_MODE=1
	
	-DARDUINO_USB_CDC_ON_BOOT=0
	
	-DARDUINO_USB_DFU_ON_BOOT=0
	
	-DARDUINO_USB_MSC_ON_BOOT=0
