#!/usr/bin/env python3
"""Generate LVGL v9 image descriptors from the project's PNG assets.

The output deliberately contains no EmbeddedGUI types. A8 assets are useful
for monochrome masks, while RGB565A8 keeps a scene's antialiased edge alpha.
"""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

try:
    from PIL import Image
except ImportError as exc:  # pragma: no cover
    raise SystemExit("Pillow is required: python -m pip install pillow") from exc


def rgb565(r: int, g: int, b: int) -> int:
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def c_bytes(values: bytes) -> str:
    rows = []
    for start in range(0, len(values), 16):
        rows.append("    " + ",".join(f"0x{value:02x}" for value in values[start:start + 16]))
    return ",\n".join(rows)


def emit_asset(source: Path, name: str, mode: str) -> str:
    image = Image.open(source).convert("RGBA")
    width, height = image.size
    pixels = list(image.getdata())
    if mode == "a8":
        payload = bytes(alpha for _, _, _, alpha in pixels)
        cf = "LV_COLOR_FORMAT_A8"
        stride = width
    else:
        rgb = bytearray()
        alpha = bytearray()
        for r, g, b, a in pixels:
            value = rgb565(r, g, b)
            rgb.extend((value & 0xff, value >> 8))
            alpha.append(a)
        payload = bytes(rgb + alpha)
        cf = "LV_COLOR_FORMAT_RGB565A8"
        stride = width * 2
    return (f"static const uint8_t {name}_data[] = {{{c_bytes(payload)}}};\n"
            f"const lv_image_dsc_t {name} = {{\n"
            f"    .header = {{ .magic = LV_IMAGE_HEADER_MAGIC, .cf = {cf}, .w = {width}, .h = {height}, .stride = {stride} }},\n"
            f"    .data_size = sizeof({name}_data), .data = {name}_data\n}};\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=Path("file/bw-64"))
    parser.add_argument("--output", type=Path, default=Path("src/lvgl_gui/resources/lvgl_weather_icons.c"))
    parser.add_argument("--mode", choices=("a8", "rgb565a8"), default="a8")
    parser.add_argument("--check", action="store_true", help="fail if output is not reproducible or stale")
    args = parser.parse_args()
    files = sorted(args.source.glob("*.png"))
    if not files:
        raise SystemExit(f"no PNG files found under {args.source}")
    digest = hashlib.sha256(b"".join(path.read_bytes() for path in files)).hexdigest()
    header = "/* Generated by tools/generate_lvgl_resources.py. Do not edit. */\n#include <lvgl.h>\n#include <stdint.h>\n\n"
    body = header + f"/* source_sha256={digest} */\n"
    symbols = []
    for index, source in enumerate(files):
        symbol = "lvgl_weather_" + source.stem.replace("-", "_").replace(".", "_")
        symbols.append(symbol)
        body += emit_asset(source, symbol, args.mode) + "\n"
    body += "const lv_image_dsc_t * const lvgl_weather_icons[] = {\n"
    body += "".join(f"    &{symbol},\n" for symbol in symbols)
    body += "};\nconst unsigned lvgl_weather_icon_count = sizeof(lvgl_weather_icons) / sizeof(lvgl_weather_icons[0]);\n\n"
    ids = [int(source.stem) for source in files if source.stem.isdigit()]
    body += "typedef struct { uint16_t id; const lv_image_dsc_t *image; } lvgl_weather_icon_entry_t;\n"
    body += "static const lvgl_weather_icon_entry_t lvgl_weather_icon_map[] = {\n"
    body += "".join(f"    {{{icon_id}U, &{symbol}}},\n" for icon_id, symbol in zip(ids, symbols))
    body += "};\n\nconst lv_image_dsc_t *lvgl_weather_icon_get(uint16_t icon_id) {\n"
    body += "    if (icon_id == 999U) return &lvgl_weather_100;\n"
    body += "    for (uint32_t i = 0U; i < sizeof(lvgl_weather_icon_map) / sizeof(lvgl_weather_icon_map[0]); ++i) {\n"
    body += "        if (lvgl_weather_icon_map[i].id == icon_id) return lvgl_weather_icon_map[i].image;\n"
    body += "    }\n"
    body += "    return &lvgl_weather_100;\n}\n"
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != body:
            raise SystemExit("LVGL resource output is stale; rerun the generator")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(body, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
