#!/usr/bin/env python3
"""Convert the legacy Home image tables into LVGL image descriptors."""
from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCES = (
    ROOT / "src" / "gui" / "resources" / "home_scene_res.c",
    ROOT / "src" / "gui" / "resources" / "home_camp_res.c",
    ROOT / "src" / "gui" / "resources" / "home_sky_objects_res.c",
)
DEFAULT_HEADER = ROOT / "include" / "gui" / "resources" / "lvgl_home_resources.h"
DEFAULT_SOURCE = ROOT / "src" / "lvgl_gui" / "resources" / "lvgl_home_resources.c"


def is_home_asset(name: str) -> bool:
    return (
        re.fullmatch(r"qoi_scene_bike[1-4]", name) is not None or
        name in {"qoi_scene_grass", "qoi_scene_grass0", "home_camp_house"} or
        re.fullmatch(r"home_camp_fire[1-4]", name) is not None or
        re.fullmatch(r"home_sky_(cloud|bird)_\d{2}", name) is not None
    )


def array_values(text: str, name: str) -> list[int]:
    match = re.search(
        rf"static\s+const\s+\w+\s+{re.escape(name)}\s*\[\s*\]\s*=\s*\{{(.*?)\}};",
        text,
        re.S,
    )
    if match is None:
        raise ValueError(f"array not found: {name}")
    return [int(value, 16) for value in re.findall(r"0x([0-9A-Fa-f]+)", match.group(1))]


def parse_assets(sources: tuple[Path, ...]) -> list[dict[str, object]]:
    assets: list[dict[str, object]] = []
    for path in sources:
        text = path.read_text(encoding="utf-8")
        for info_match in re.finditer(
            r"static\s+const\s+egui_image_std_info_t\s+(\w+)_info\s*=\s*\{(.*?)\};",
            text,
            re.S,
        ):
            name, body = info_match.groups()
            data_name = re.search(r"\.data_buf\s*=\s*(\w+)", body)
            alpha_name = re.search(r"\.alpha_buf\s*=\s*(\w+)", body)
            width = re.search(r"\.width\s*=\s*(\d+)", body)
            height = re.search(r"\.height\s*=\s*(\d+)", body)
            if not data_name or not width or not height:
                raise ValueError(f"invalid image info: {name}")
            data_symbol = data_name.group(1)
            data_is_alpha = data_symbol.endswith("_alpha")
            data = array_values(text, data_symbol)
            alpha = (array_values(text, alpha_name.group(1))
                     if alpha_name and alpha_name.group(1) != "NULL" else None)
            if not is_home_asset(name):
                continue
            assets.append({
                "name": name,
                "width": int(width.group(1)),
                "height": int(height.group(1)),
                "data": data,
                "data_is_alpha": data_is_alpha,
                "alpha": alpha,
            })
    assets.sort(key=lambda item: str(item["name"]))
    return assets


def bytes_hex(values: bytes) -> str:
    rows = []
    for start in range(0, len(values), 16):
        rows.append("    " + ",".join(f"0x{value:02x}" for value in values[start:start + 16]))
    return ",\n".join(rows)


def emit_header(assets: list[dict[str, object]]) -> str:
    lines = [
        "#pragma once",
        "",
        "#include <lvgl.h>",
        "",
    ]
    for asset in assets:
        lines.append(f"extern const lv_image_dsc_t {asset['name']};")
    lines.extend(["", "extern const lv_image_dsc_t * const lvgl_home_bikes[];",
                  "extern const unsigned lvgl_home_bike_count;",
                  "extern const lv_image_dsc_t * const lvgl_home_fires[];",
                  "extern const unsigned lvgl_home_fire_count;",
                  "extern const lv_image_dsc_t * const lvgl_home_clouds[];",
                  "extern const unsigned lvgl_home_cloud_count;",
                  "extern const lv_image_dsc_t * const lvgl_home_birds[];",
                  "extern const unsigned lvgl_home_bird_count;",
                  "extern const lv_image_dsc_t * const lvgl_home_grass_tiles[];",
                  "extern const unsigned lvgl_home_grass_tile_count;",
                  "extern const lv_image_dsc_t * const lvgl_home_grass_bases[];",
                  "extern const unsigned lvgl_home_grass_base_count;",
                  "extern const lv_image_dsc_t * const lvgl_home_house[];",
                  "extern const unsigned lvgl_home_house_count;",
                  ""])
    return "\n".join(lines)


def emit_source(assets: list[dict[str, object]], digest: str) -> str:
    lines = ["/* Generated by tools/generate_lvgl_home_resources.py. Do not edit. */",
             "#include <lvgl.h>", "#include <stdint.h>", "",
             f"/* source_sha256={digest} */", ""]
    for asset in assets:
        name = str(asset["name"])
        width = int(asset["width"])
        height = int(asset["height"])
        data_values = list(asset["data"])
        data_is_alpha = bool(asset["data_is_alpha"])
        alpha_values = asset["alpha"]
        if data_is_alpha:
            payload = bytes(data_values)
            cf = "LV_COLOR_FORMAT_A8"
            stride = width
        else:
            rgb = bytearray()
            for value in data_values:
                rgb.extend((int(value) & 0xff, (int(value) >> 8) & 0xff))
            if alpha_values is None:
                alpha_values = [255] * (width * height)
            payload = bytes(rgb + bytearray(int(value) & 0xff for value in alpha_values))
            cf = "LV_COLOR_FORMAT_RGB565A8"
            stride = width * 2
        lines.append(f"static const uint8_t {name}_data[] = {{")
        lines.append(bytes_hex(payload))
        lines.append("};")
        lines.append(f"const lv_image_dsc_t {name} = {{")
        lines.append(f"    .header = {{ .magic = LV_IMAGE_HEADER_MAGIC, .cf = {cf}, .w = {width}, .h = {height}, .stride = {stride} }},")
        lines.append(f"    .data_size = sizeof({name}_data), .data = {name}_data")
        lines.append("};\n")

    def table(symbol: str, count_symbol: str, predicate: str) -> None:
        selected = [str(asset["name"]) for asset in assets if re.match(predicate, str(asset["name"]))]
        lines.append(f"const lv_image_dsc_t * const {symbol}[] = {{")
        lines.extend(f"    &{name}," for name in selected)
        lines.append("};")
        lines.append(f"const unsigned {count_symbol} = sizeof({symbol}) / sizeof({symbol}[0]);\n")

    table("lvgl_home_bikes", "lvgl_home_bike_count", r"qoi_scene_bike[1-4]$")
    table("lvgl_home_fires", "lvgl_home_fire_count", r"home_camp_fire[1-4]$")
    table("lvgl_home_clouds", "lvgl_home_cloud_count", r"home_sky_cloud_\d{2}$")
    table("lvgl_home_birds", "lvgl_home_bird_count", r"home_sky_bird_\d{2}$")
    table("lvgl_home_grass_tiles", "lvgl_home_grass_tile_count", r"qoi_scene_grass$")
    table("lvgl_home_grass_bases", "lvgl_home_grass_base_count", r"qoi_scene_grass0$")
    table("lvgl_home_house", "lvgl_home_house_count", r"home_camp_house$")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--header", type=Path, default=DEFAULT_HEADER)
    parser.add_argument("--output", type=Path, default=DEFAULT_SOURCE)
    args = parser.parse_args()
    assets = parse_assets(DEFAULT_SOURCES)
    digest = hashlib.sha256(b"".join(path.read_bytes() for path in DEFAULT_SOURCES)).hexdigest()
    header = emit_header(assets)
    source = emit_source(assets, digest)
    if args.check:
        if not args.header.exists() or args.header.read_text(encoding="utf-8") != header:
            raise SystemExit("LVGL Home header is stale; rerun the generator")
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != source:
            raise SystemExit("LVGL Home resource output is stale; rerun the generator")
        return
    args.header.parent.mkdir(parents=True, exist_ok=True)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.header.write_text(header, encoding="utf-8", newline="\n")
    args.output.write_text(source, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
