#!/usr/bin/env python3
"""Generate solid Alpha8 outlines from the restored Classic cloud masks."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCENE_SOURCE = ROOT / "src" / "gui" / "resources" / "home_scene_res.c"
HEADER_PATH = ROOT / "include" / "gui" / "resources" / "home_cloud_outline_res.h"
SOURCE_PATH = ROOT / "src" / "gui" / "resources" / "home_cloud_outline_res.c"
CLOUDS = ("qoi_scene_cloud1", "qoi_scene_cloud2")
OUTLINE_RADIUS = 2


def read_cloud(source: str, name: str) -> tuple[int, int, bytes]:
    alpha_match = re.search(
        rf"static const uint8_t {name}_alpha\[\] = \{{(.*?)\}};",
        source,
        re.DOTALL,
    )
    info_match = re.search(
        rf"static const egui_image_std_info_t {name}_info = \{{(.*?)\}};",
        source,
        re.DOTALL,
    )
    if alpha_match is None or info_match is None:
        raise ValueError(f"missing cloud resource: {name}")
    width = int(re.search(r"\.width = (\d+),", info_match.group(1)).group(1))
    height = int(re.search(r"\.height = (\d+),", info_match.group(1)).group(1))
    alpha = bytes(int(value, 16) for value in re.findall(r"0x([0-9A-Fa-f]{2})", alpha_match.group(1)))
    if len(alpha) != width * height:
        raise ValueError(f"{name}: alpha length {len(alpha)} != {width}x{height}")
    return width, height, alpha


def make_outline(width: int, height: int, alpha: bytes) -> bytes:
    solid = [value >= 128 for value in alpha]
    outline = bytearray(width * height)
    for y in range(height):
        for x in range(width):
            index = y * width + x
            if not solid[index]:
                continue
            boundary = False
            for dy in range(-OUTLINE_RADIUS, OUTLINE_RADIUS + 1):
                for dx in range(-OUTLINE_RADIUS, OUTLINE_RADIUS + 1):
                    nx, ny = x + dx, y + dy
                    if nx < 0 or nx >= width or ny < 0 or ny >= height or not solid[ny * width + nx]:
                        boundary = True
                        break
                if boundary:
                    break
            if boundary:
                outline[index] = 255
    return bytes(outline)


def format_bytes(data: bytes) -> str:
    return "\n".join(
        "    " + ", ".join(f"0x{value:02X}" for value in data[offset : offset + 16]) + ","
        for offset in range(0, len(data), 16)
    )


def main() -> None:
    source = SCENE_SOURCE.read_text(encoding="utf-8")
    generated: list[tuple[str, int, int, bytes]] = []
    for index, name in enumerate(CLOUDS, start=1):
        width, height, alpha = read_cloud(source, name)
        outline = make_outline(width, height, alpha)
        if not any(outline):
            raise ValueError(f"{name}: generated outline is empty")
        generated.append((f"home_cloud{index}_outline", width, height, outline))

    header = '''#ifndef __HOME_CLOUD_OUTLINE_RES_H__
#define __HOME_CLOUD_OUTLINE_RES_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "image/egui_image_std.h"

#if EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_ALPHA_8
extern const egui_image_std_t home_cloud1_outline;
extern const egui_image_std_t home_cloud2_outline;
#endif

#ifdef __cplusplus
}
#endif

#endif /* __HOME_CLOUD_OUTLINE_RES_H__ */
'''
    lines = [
        '#include "gui/resources/home_cloud_outline_res.h"',
        "",
        "#include <stddef.h>",
        "",
        "#if EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_ALPHA_8",
        "",
        "// Generated by tools/generate_home_cloud_outlines.py. Do not edit by hand.",
    ]
    for name, width, height, outline in generated:
        lines += [
            "",
            f"static const uint8_t {name}_alpha[] = {{",
            format_bytes(outline),
            "};",
            "",
            f"static const egui_image_std_info_t {name}_info = {{",
            f"    .data_buf = {name}_alpha,",
            "    .alpha_buf = NULL,",
            "    .data_type = EGUI_IMAGE_DATA_TYPE_ALPHA,",
            "    .alpha_type = EGUI_IMAGE_ALPHA_TYPE_8,",
            "    .res_type = EGUI_RESOURCE_TYPE_INTERNAL,",
            f"    .width = {width},",
            f"    .height = {height},",
            "};",
            "",
            f"extern const egui_image_std_t {name};",
            f"EGUI_IMAGE_SUB_DEFINE_CONST(egui_image_std_t, {name}, &{name}_info);",
        ]
    lines += ["", "#endif /* EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_ALPHA_8 */", ""]
    HEADER_PATH.write_text(header, encoding="ascii", newline="\n")
    SOURCE_PATH.write_text("\n".join(lines), encoding="ascii", newline="\n")
    print(f"generated {len(generated)} solid cloud outlines")


if __name__ == "__main__":
    main()
