#!/usr/bin/env python3
"""Generate RGB565 + Alpha8 EmbeddedGUI weather resources."""

from __future__ import annotations

from pathlib import Path

from PIL import Image

ICON_SIZE = 64
ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "data" / "bw-64"
if not SOURCE_DIR.is_dir():
    SOURCE_DIR = ROOT / "file" / "bw-64"
HEADER_PATH = ROOT / "include" / "gui" / "resources" / "icons.h"
SOURCE_PATH = ROOT / "src" / "gui" / "resources" / "icons.c"


def read_icon(path: Path) -> tuple[list[int], bytes]:
    with Image.open(path) as image:
        rgba = image.convert("RGBA")
    if rgba.size != (ICON_SIZE, ICON_SIZE):
        raise ValueError(f"{path.name}: expected 64x64, got {rgba.width}x{rgba.height}")
    pixels = list(rgba.getdata())
    rgb565: list[int] = []
    alpha = bytearray()
    for red, green, blue, opacity in pixels:
        rgb565.append(((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3))
        alpha.append(opacity)
    return rgb565, bytes(alpha)


def format_values(values: list[int], width: int = 12) -> str:
    rows = []
    for offset in range(0, len(values), width):
        rows.append("    " + ", ".join(f"0x{value:04X}" for value in values[offset : offset + width]) + ",")
    return "\n".join(rows)


def format_bytes(data: bytes) -> str:
    return "\n".join(
        "    " + ", ".join(f"0x{value:02X}" for value in data[offset : offset + 16]) + ","
        for offset in range(0, len(data), 16)
    )


def generate_header() -> str:
    return '''#ifndef __WEATHER_ICONS_H__
#define __WEATHER_ICONS_H__

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include "image/egui_image_std.h"

#define WEATHER_ICON_SIZE 64U
#define WEATHER_ICON_PIXELS (WEATHER_ICON_SIZE * WEATHER_ICON_SIZE)
#define WEATHER_ICON_RGB565_BYTES (WEATHER_ICON_PIXELS * 2U)
#define WEATHER_ICON_ALPHA8_BYTES WEATHER_ICON_PIXELS

#if EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565
const egui_image_std_t *ui_weather_icon_get(uint16_t icon_id);
const egui_image_std_t *ui_weather_icon_get_mask(uint16_t icon_id);
#endif

#ifdef __cplusplus
}
#endif

#endif /* __WEATHER_ICONS_H__ */
'''


def generate_source(icons: list[tuple[int, list[int], bytes]]) -> str:
    lines = [
        '#include "gui/resources/icons.h"',
        "",
        "#include <stddef.h>",
        "",
        "#if EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565",
        "",
        "// Generated by tools/generate_weather_icons.py. Do not edit by hand.",
    ]
    for code, pixels, alpha in icons:
        lines += [
            "",
            f"static const uint16_t weather_icon_{code}_data[WEATHER_ICON_PIXELS] = {{",
            format_values(pixels),
            "};",
            "",
            f"static const uint8_t weather_icon_{code}_alpha[WEATHER_ICON_ALPHA8_BYTES] = {{",
            format_bytes(alpha),
            "};",
            "",
            f"static const egui_image_std_info_t weather_icon_{code}_info = {{",
            f"    .data_buf = weather_icon_{code}_data,",
            f"    .alpha_buf = weather_icon_{code}_alpha,",
            "    .data_type = EGUI_IMAGE_DATA_TYPE_RGB565,",
            "    .alpha_type = EGUI_IMAGE_ALPHA_TYPE_8,",
            "    .res_type = EGUI_RESOURCE_TYPE_INTERNAL,",
            "    .width = WEATHER_ICON_SIZE,",
            "    .height = WEATHER_ICON_SIZE,",
            "};",
            "",
            f"extern const egui_image_std_t weather_icon_{code};",
            f"EGUI_IMAGE_SUB_DEFINE_CONST(egui_image_std_t, weather_icon_{code}, &weather_icon_{code}_info);",
            "",
            f"static const egui_image_std_info_t weather_icon_{code}_mask_info = {{",
            f"    .data_buf = weather_icon_{code}_alpha,",
            "    .alpha_buf = NULL,",
            "    .data_type = EGUI_IMAGE_DATA_TYPE_ALPHA,",
            "    .alpha_type = EGUI_IMAGE_ALPHA_TYPE_8,",
            "    .res_type = EGUI_RESOURCE_TYPE_INTERNAL,",
            "    .width = WEATHER_ICON_SIZE,",
            "    .height = WEATHER_ICON_SIZE,",
            "};",
            "",
            f"extern const egui_image_std_t weather_icon_{code}_mask;",
            f"EGUI_IMAGE_SUB_DEFINE_CONST(egui_image_std_t, weather_icon_{code}_mask, &weather_icon_{code}_mask_info);",
        ]
    lines += [
        "",
        "typedef struct { uint16_t icon_id; const egui_image_std_t *image; const egui_image_std_t *mask; } weather_icon_map_t;",
        "static const weather_icon_map_t s_weather_icons[] = {",
    ]
    lines += [f"    {{{code}U, &weather_icon_{code}, &weather_icon_{code}_mask}}," for code, _, _ in icons]
    lines += [
        "};",
        "",
        "const egui_image_std_t *ui_weather_icon_get(uint16_t icon_id)",
        "{",
        "    for (uint32_t i = 0U; i < (sizeof(s_weather_icons) / sizeof(s_weather_icons[0])); i++)",
        "    {",
        "        if (s_weather_icons[i].icon_id == icon_id) return s_weather_icons[i].image;",
        "    }",
        "    return &weather_icon_999;",
        "}",
        "",
        "const egui_image_std_t *ui_weather_icon_get_mask(uint16_t icon_id)",
        "{",
        "    for (uint32_t i = 0U; i < (sizeof(s_weather_icons) / sizeof(s_weather_icons[0])); i++)",
        "    {",
        "        if (s_weather_icons[i].icon_id == icon_id) return s_weather_icons[i].mask;",
        "    }",
        "    return &weather_icon_999_mask;",
        "}",
        "",
        "#endif /* EGUI_CONFIG_FUNCTION_IMAGE_FORMAT_RGB565 */",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    paths = sorted(SOURCE_DIR.glob("*.png"), key=lambda path: path.name)
    if not paths:
        raise ValueError(f"no PNG files found in {SOURCE_DIR}")
    icons: list[tuple[int, list[int], bytes]] = []
    codes: set[int] = set()
    for path in paths:
        if not path.stem.isdigit():
            raise ValueError(f"{path.name}: filename must be a numeric weather code")
        code = int(path.stem)
        if code in codes:
            raise ValueError(f"duplicate weather code: {code}")
        codes.add(code)
        pixels, alpha = read_icon(path)
        if len(pixels) != WEATHER_ICON_PIXELS or len(alpha) != WEATHER_ICON_PIXELS:
            raise ValueError(f"{path.name}: invalid generated buffer length")
        icons.append((code, pixels, alpha))
    if 999 not in codes:
        raise ValueError("999.png is required as the unknown-weather fallback")
    HEADER_PATH.write_text(generate_header(), encoding="ascii", newline="\n")
    SOURCE_PATH.write_text(generate_source(icons), encoding="ascii", newline="\n")
    print(f"generated {len(icons)} weather icons ({len(icons) * WEATHER_ICON_PIXELS * 3} bytes)")


WEATHER_ICON_PIXELS = ICON_SIZE * ICON_SIZE

if __name__ == "__main__":
    main()
